name: CMake MSVC x86 Build & Upload Release
on:
  push:
    tags:
      - "v*" # 仅推送版本标签时构建发布
  workflow_dispatch: # 支持手动触发构建

env:
  BUILD_DIR: build_win32
  CONFIG: Release
  ARCH: Win32

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup MSVC x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: CMake Configure
        run: |
          mkdir ${{ env.BUILD_DIR }}
          cd ${{ env.BUILD_DIR }}
          cmake .. -A ${{ env.ARCH }}

      - name: CMake Build
        run: |
          cd ${{ env.BUILD_DIR }}
          cmake --build . --config ${{ env.CONFIG }} --parallel

      # 打包产物
      - name: Package file
        run: |
          mkdir output
          Copy-Item "$env:BUILD_DIR\Release\strom80.mix" output\
          Compress-Archive -Path output\strom80.mix -DestinationPath output\win32-release.zip

      # 上传到Release资产
      - name: Upload binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            output/strom80.mix
            output/win32-release.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          